# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.1.0
maven_group = dev.ultreon.mods.materialistic
archives_name = materialistic
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.2

# Dependencies
architectury_api_version = 21.0.7
fabric_loader_version = 0.19.5
fabric_api_version = 0.160.0+26.2
neoforge_version = 26.2.0.52-beta
